apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./applications/overlays/prod
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vanitydomain
      namespace: prod-vanitydomain
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sklonger
      namespace: prod-sklonger
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: config-reload-demo
      namespace: prod-config-reload-demo
  postBuild:
    substitute:
      release_env: prod
      base_uri: coryb.xyz
      sklonger_domain: sklonger.app
      demo_domain: demo.coryb.xyz
