apiVersion: v1
kind: Secret
metadata:
    name: config-reload-demo-secrets
    namespace: ${release_env}-config-reload-demo
stringData:
    databaseUrl: ENC[AES256_GCM,data:Y7a/eLRK+YTYtFMPLvHzw/k+b/3p386DHFYhCJTFktV5tVeD3aSE0g==,iv:JkcPGbxnEiGo0kT8GVIm9q02/Px0w/+AeHnyuT0sUeg=,tag:nNx4QtEO0rhq6EEb12bPLg==,type:str]
    apiKey: ENC[AES256_GCM,data:xBeMqg+LHYofrXFT,iv:txiBbN9MaQLqL+DOKN+0speOHPvHt2JXamT8Zqrj3Xk=,tag:PArkzbHtK5Vt65rkYrs0ig==,type:str]
sops:
    age:
        - recipient: age1rdp8qhyu7wng3k4jte5t6yq43nqg9m5yud9p3n6gccvchh0kf4qsdkxv7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UUxKc2crV0N2ZkF6d1I5
            OGV1dzBtTGtBZVFNd0YwUHVneXVRNjRSdHpjCld3dlBHT2E5aG9oMWUySWhta2FH
            dmxjV1lONUFaMmIyYTMybytPWHVGQkkKLS0tIEFWZGVMK2dQbW1GWVNFbHhVWlB1
            VVlHZFA1R2Vad3hqbGNMN3J2VXFvUGsK1Krh83Vq+O55Wjtiglb7uohevLGodDhp
            jubp//x1emjzkVSGT9Tgguh72BVrbCHpXmr710hcFnnAK9kv1uFezg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T02:17:35Z"
    mac: ENC[AES256_GCM,data:klyDCOmrPVywLNMYLLau7OBxZjFdQGo+Fm0FzLe5p11Hn3BYNS/nHSCYToVMRiEvIhvZREVLdl0GrELI42kjUt+Z10mgNLZ7QYm+xeq0CROH+P0VoFePmBEEZdb/kP1GqUDsffkgzHS+hrPyA0pu+RQHaBveVW6GDF1JbhikrWM=,iv:CC/nV7MyygOJ9lL82E9rouuKPI68CX4Xq0Oo7ihu/a0=,tag:6qRg5equAU7pMdlpJR3Wbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
