apiVersion: v1
kind: Secret
metadata:
    name: config-reload-demo-secrets
    namespace: ${release_env}-config-reload-demo
stringData:
    databaseUrl: ENC[AES256_GCM,data:hw9L/dbCsYmv/M6eit2m9Xy55475byeBhALpB7xdYwYbNTAARPIyEA==,iv:sLMPK76Dqjsz+kFpD1Z66qqnlcInaigGgNj2pouyIGY=,tag:uz4IIgJqkqYDtqVdJjIUyQ==,type:str]
    apiKey: ENC[AES256_GCM,data:5Ds5OBSGuPNJ+JOhTb4=,iv:oZDVCP/xQPFXbocZJRzekIhfsFlbiRhDRJDyl0dDE2s=,tag:egKHNw0G54tLpnvN4gVBzw==,type:str]
sops:
    age:
        - recipient: age1rdp8qhyu7wng3k4jte5t6yq43nqg9m5yud9p3n6gccvchh0kf4qsdkxv7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd2c4V0V1U0hmMjI0d3Yy
            aTArV1duL0RHamt0aTVCVTVaelpveUYyZ1EwCkxHaHNzSmRTZjRHM2N5QjFaWlBS
            aGF5Ym12ZWZiRHJPa0VnTGxOeWVKa2MKLS0tIHdPc041cVNPbW5Lc0NnRGdPV3hW
            cFpmOHFPMkR6RGZRby9rWERqQ1ZiODQKou0l3X+rP2aZIZJMLvZwFk6HTgJXqOLZ
            YFPqjThvxZjSti7DzXikkL+MbvCt/A7euDO5xhAdDt5dgNQB6tCM3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:32:41Z"
    mac: ENC[AES256_GCM,data:p2nk0G+ISrayHW4b6vYhIqQitlvssrTx2RN9/kDn2GTG264f0VJRwRIly58mzoAbQnXt6++Yioy/Yw4L8RGaxLzOtN/NVqckiw0b6QCCIpewEnnUBpGI6hYKC9K9a6fQ5BSGfQFcQ0iwEYyicS1/+svpQyQxGlsEO8HT6DufkHg=,iv:O3eFzXUCmhGR54WDFk4alR8bEVAd2W+OwxMZekglwic=,tag:HlKUaO5fMNtA3NpgyC2nGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
