apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: config-reload-demo-http-redirect
  namespace: ${release_env}-config-reload-demo
spec:
  hostnames:
    - "${demo_domain}"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: web
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/acme-challenge/
      backendRefs: []
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: config-reload-demo-https
  namespace: ${release_env}-config-reload-demo
spec:
  hostnames:
    - "${demo_domain}"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: websecure-demo
  rules:
    - backendRefs:
        - name: config-reload-demo
          port: 80
