apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config-reload-demo-helmrelease.yaml
  - config-reload-demo-certificate.yaml
  - config-reload-demo-httproute.yaml
  - secrets/config-reload-demo-secrets.yaml
